### ISSUE TITLE
wit.ai does not work. google - work

### ISSUE THREAD

**Issue by ruvhell** [antirek/voicer#22]
[root@freepbx config]# pm2 logs voicer [--lines 1000]
[TAILING] Tailing last 15 lines for [voicer] process (change the value with --lines option)
/root/.pm2/logs/voicer-out.log last 15 lines:

/root/.pm2/logs/voicer-error.log last 15 lines:
0|voicer   |         ntick: true,
0|voicer   |         _started: true,
0|voicer   |         href: 'https://api.wit.ai/speech',
0|voicer   |         req: [Object],
0|voicer   |         response: [Circular],
0|voicer   |         originalHost: 'api.wit.ai',
0|voicer   |         originalHostHeaderName: 'host',
0|voicer   |         responseContent: [Circular],
0|voicer   |         _destdata: true,
0|voicer   |         _ended: true,
0|voicer   |         _callbackCalled: true },
0|voicer   |      toJSON: [Function: responseToJSON],
0|voicer   |      caseless: Caseless { dict: [Object] },
0|voicer   |      read: [Function],
0|voicer   |      body: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 20 3a 20 22 42 61 64 20 61 75 74 68 2c 20 63 68 65 63 6b 20 74 6f 6b 65 6e 2f 70 61 72 61 6d 73 22 2c 0a 20 20 22 63 ... > } }

**Comment by antirek** [comment]
fixed in 0.2.1
